[package]
name = "lrlex"
description = "Simple lexer generator"
repository = "https://github.com/softdevteam/grmtools"
version = "0.12.0"
authors = ["Laurence Tratt <http://tratt.net/laurie/>"]
edition = "2021"
readme = "README.md"
license = "Apache-2.0/MIT"
categories = ["parsing"]

[[bin]]
doc = false
name = "lrlex"

[lib]
name = "lrlex"
path = "src/lib/mod.rs"

[build-dependencies]
vergen = { version = "7", default-features = false, features = ["build"] }

[dependencies]
getopts = "0.2" # only needed for src/main.rs
lazy_static = "1.4"
lrpar = { path = "../lrpar", version = "0.12" }
regex = "1"
num-traits = "0.2"
serde = "1.0"
try_from = "0.3"
ropey = { version = "1.4.1", optional=true }

[features]
default = []
rope = ["ropey"]
